### ISSUE TITLE
Zeroes for blank values

### ISSUE THREAD

**Issue by mcandre** [plinss/sem_ver#1]
Practically speaking, many version numbers omit patch and/or minor values. This isn't strictly speaking semver, but I wonder if we could reasonably handle such cases with zeros most of the time?

**Comment by plinss** [comment]
Are you looking to be able to parse such version numbers? e.g. interpret "1.0" as "1.0.0"?

**Comment by plinss** [comment]
Added `force` classmethod, should accept most non-SemVer version strings and convert.
